import Vue from 'vue';
import VueI18n from 'vue-i18n';

Vue.use(VueI18n);
const messages = {
    en: {

        bangla: 'বাংলা',
        english: 'English',
        home: 'Home',
        apply_now: 'Apply Now',
        about: 'About',
        jobs: 'Jobs',
        blog: 'Blog',
        contact: 'Contact',
        language: 'Language',
        my_profile: 'My Profile',
        logout: 'Logout',
        login: 'Login',
        post_a_job: 'Post A Job',
        job_portal: 'Job Portal',
        user_avatar: 'User Avatar',
        applied_jobs: 'Applied Jobs',
        saved_jobs: 'Saved Jobs',
        update_profile: 'Update Profile',
        job: 'Job',
        title: 'Title',
        application_date: 'Application Date',
        location: 'Location',
        status: 'Status',
        interview: 'Interview',
        interview_information: 'Interview Information',
        search_results: 'Search Results',
        search: 'Search',
        explore_by_category: 'Explore By Category',
        job_listing: 'Job Listing',
        newsletter: 'Newsletter',
        company: 'Company',
        job_list: 'Job List',
        job_category: 'Job Category',
        our_blog_news: 'Our Blog News',
        our_trusted_clients: 'Our Trusted Clients',
        comments: 'Comments',
        leave_a_comment: 'Leave a Comment',
        submit: 'Submit',
        saved_job: 'Saved Job',
        read_more: 'Read More',
        more: 'More',
        notice: 'Notice',
        blog_Article: 'Blog & Article',
        remote: 'Remote',
        full_time: 'Full Time',
        part_time: 'Part Time',
        not_specified: 'Not Specified',
        apply_now_or_view: 'Apply Now Or View',
        save_job: 'Save Job',
        keywordsearch: 'keyword Search',
        important_links: 'Important Links',
        newsletter_intro: 'Newsletter Intro',
        about_us: 'About Us',
        contact_us: 'Contact Us',
        privacy_policy: 'Privacy Policy',
        terms_condition: 'Terms & Condition',
        subscribe: 'Subscribe',
        remove:'Remove',
        name: 'Name',
        email: 'Email',
        phone: 'Phone',
        address: 'Address',
        skill: 'Skill',
        education: 'Education',
        experience: 'Experience',
        uploadImage: 'Upload Image',
        bio: 'Bio',
        updateProfile: 'Update Profile',
        update: 'Update',
        interviewSchedule: 'Interview Schedule',
        interviewStatus: 'Interview Status',
        interviewTable: 'Interview Notice Table',
        cookies: 'Cookies',
        help: 'Help',
        faqs: 'FAQs',
        type: 'Type',
        applied: 'Login Before Apply',
        comment: 'Login Before Comment'



    },
    bn: {
        bangla: 'বাংলা',
        english: 'English',
        home: 'হোম',
        apply_now: 'এখনই আবেদন করুন',
        about: 'সম্পর্কিত',
        jobs: 'চাকরি',
        blog: 'ব্লগ',
        contact: 'যোগাযোগ',
        my_profile: 'আমার প্রোফাইল',
        logout: 'লগআউট',
        login: 'লগইন',
        post_a_job: 'একটি চাকরি পোস্ট করুন',
        language: 'ভাষা',
        job_portal: 'চাকরি পোর্টাল',
        user_avatar: 'ব্যবহারকারী আভাটার',
        applied_jobs: 'আবেদনকৃত চাকরী',
        saved_jobs: 'সংরক্ষিত চাকরী',
        update_profile: 'প্রোফাইল আপডেট করুন',
        job: 'চাকরি',
        title: 'শিরোনাম',
        application_date: 'আবেদন তারিখ',
        location: 'অবস্থান',
        status: 'অবস্থা',
        interview: 'সাক্ষাৎকার',
        notice: 'লক্ষ্য করুন',
        interviewStatus: 'সাক্ষাৎকার অবস্থা',
        InterviewTable: 'সাক্ষাৎকার নোটিশ টেবিল',
        interview_information: 'সাক্ষাৎকারের তথ্য',
        search_results: 'অনুসন্ধানের ফলাফল',
        search: 'অনুসন্ধান করুন',
        explore_by_category: 'ক্যাটেগরিতে অনুসন্ধান করুন',
        job_listing: 'চাকরির তালিকা',
        newsletter: 'নিউজলেটার',
        company: 'কোম্পানি',
        job_list: 'চাকরির তালিকা',
        job_category: 'চাকরির ক্যাটেগরি',
        keywordsearch: 'কীওয়ার্ড অনুসন্ধান',
        our_blog_news: 'আমাদের ব্লগ সংবাদ',
        our_trusted_clients: 'আমাদের বিশ্বস্ত ক্লায়েন্ট',
        comments: 'মন্তব্য',
        leave_a_comment: 'মন্তব্য করুন',
        submit: 'জমা দিন',
        saved_job: 'সংরক্ষিত চাকরি',
        read_more: 'আরও পড়ুন',
        more: 'আরও',
        blog_Article: 'ব্লগ এবং নিবন্ধ',
        remote: 'রিমোট',
        full_time: 'পূর্ণকালীন',
        part_time: 'আংশিককালীন',
        not_specified: 'নির্ধারিত নয়',
        apply_now_or_view: 'এখনই আবেদন করুন অথবা দেখুন',
        save_job: 'চাকরি সংরক্ষণ করুন',
        important_links: 'গুরুত্বপূর্ণ লিংক',
        newsletter_intro: 'নিউজলেটার',
        about_us: 'আমাদের সম্পর্কে',
        contact_us: 'যোগাযোগ করুন',
        privacy_policy: 'গোপনীয়তা নীতি',
        terms_condition: 'শর্তাবলী',
        subscribe: 'সাবস্ক্রাইব',
        remove:'অপসারণ',
        name: 'নাম',
        email: 'ইমেইল',
        phone: 'ফোন',
        address: 'ঠিকানা',
        skill: 'দক্ষতা',
        education: 'শিক্ষা',
        experience: 'অভিজ্ঞতা',
        uploadImage: 'ছবি আপলোড করুন',
        bio: 'জীবনবৃত্তান্ত',
        updateProfile: 'প্রোফাইল আপডেট করুন',
        update: 'আপডেট',
        interviewSchedule: 'সাক্ষাৎকারের সময়সূচি',
        interviewTable: 'সাক্ষাৎকারের টেবিল',
        cookies: 'কুকিজ',
        help: 'সাহায্য',
        faqs: 'প্রশ্নোত্তর',
        type: 'ধরণ',
        applied: 'আবেদন করার পূর্বে লগইন করুন',
        comment: 'কমেন্ট করার আগে লগইন করুন',

    },
};

const savedLanguage = localStorage.getItem('selectedLanguage') || 'en';

const i18n = new VueI18n({
    locale: savedLanguage,
    messages,
});


export default i18n;
